spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DBURL}/${DB}
    username: ${DBUSER}
    password: ${DBPASSWORD}
#
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#    password: qwer1234


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
